# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alex Piccolo
email: alexpiccolo+blog@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Created using Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PiccoloSunday
github_username:  piccoloa
linkedin_username: alex-piccolo-cfa
linkedin_name: Alex Piccolo
#so_username: briancaffey
#so_link: 6084948/briancaffey
#steemit_name: mrbrian
#steemit_username: mrbrian

# Build settings
markdown: kramdown
highlighter: rouge

#plugins:
#  - jekyll-feed

#not included in piccoloa--- believe this referes to documentation
collections:
 projects:
   output: true
   permalink: /:collection/:path

# Site menu settings
menu:
  - title: "Contact"
    url: "/contact"
  - title: "Blog"
    url: "/blog"
  - title: "Projects"
    url: "/projects"
  - title: "Resume"
    url: "/resume"
# End


category_order:
  - 'Exploring Big Data'
  - 'Projects'
  # - 'Advanced'
  # - 'Platforms'
  # - 'Plugins'
  # - 'Samples'
  # - 'Tutorials'
  # - 'Upgrading'
  # - 'Contributing'






# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
